CREATE TABLE code (
id INT AUTO_INCREMENT NOT NULL COMMENT 'ID', PRIMARY KEY (id),
code_id VARCHAR(50) NOT NULL COMMENT 'コード ID',
display_name VARCHAR(100) NOT NULL COMMENT '表示名',
description TEXT NOT NULL COMMENT '説明',
sort_order INT(10) DEFAULT 0 COMMENT '表示順'
)ENGINE=InnoDB ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_general_ci COMMENT='コード';
