CREATE TABLE koumoku (
id INT AUTO_INCREMENT NOT NULL COMMENT 'ID', PRIMARY KEY (id),
koumoku_id VARCHAR(50) NOT NULL COMMENT '項目ID',
display_name VARCHAR(100) NOT NULL COMMENT '表示名',
description TEXT NOT NULL COMMENT '説明'
)ENGINE=InnoDB ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_general_ci COMMENT='項目';
