CREATE TABLE message (
id INT AUTO_INCREMENT NOT NULL COMMENT 'ID', PRIMARY KEY (id),
message_id VARCHAR(50) NOT NULL COMMENT 'メッセージ ID',
display_name VARCHAR(100) NOT NULL COMMENT '表示名',
description TEXT NOT NULL COMMENT '説明'
)ENGINE=InnoDB ROW_FORMAT=DYNAMIC COLLATE=utf8mb4_general_ci COMMENT='メッセージ';
